### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LocoR9** [jkbenaim/hs100#15]
what does this means?

`<html>
<body>

hs100.0 | 2023-02-18 09:22:29.514 | error | TCP Timeout after 10000ms192.168.178.34:9999 {"emeter":{"get_realtime":{}}}
-- | -- | -- | --
hs100.0 | 2023-02-18 09:22:29.513 | error | Error: TCP Timeout after 10000ms192.168.178.34:9999 {"emeter":{"get_realtime":{}}} at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
hs100.0 | 2023-02-18 09:22:29.513 | error | unhandled promise rejection: TCP Timeout after 10000ms192.168.178.34:9999 {"emeter":{"get_realtime":{}}}
hs100.0 | 2023-02-18 09:22:29.508 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hs100.0 | 2023-02-18 04:26:29.114 | error | TCP Timeout after 10000ms192.168.178.34:9999 {"emeter":{"get_monthstat":{"year":2023}}}
hs100.0 | 2023-02-18 04:26:29.114 | error | Error: TCP Timeout after 10000ms192.168.178.34:9999 {"emeter":{"get_monthstat":{"year":2023}}} at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
hs100.0 | 2023-02-18 04:26:29.113 | error | unhandled promise rejection: TCP Timeout after 10000ms192.168.178.34:9999 {"emeter":{"get_monthstat":{"year":2023}}}
hs100.0 | 2023-02-18 04:26:29.109 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

**Comment by jkbenaim** [comment]
Sir, I think you are confused. The error you posted is not from my program. Please consult the author of the program you are using.
