### ISSUE TITLE
Any possibility of getting this to work with KP125MP2?

### ISSUE THREAD

**Issue by puterboy** [jkbenaim/hs100#19]
KP125MP2 is a Kasa/TP-Link mini-smart plug with Energy Monitoring and Matter support.
I would be satisfied if I could just turn it on/off -- though access to the energy consumption part would be cool too!

**Comment by jkbenaim** [comment]
Seems like a neat little plug. I'll buy one and see what I can do.

**Comment by puterboy** [comment]
It truly is a nice plug.
Note that there is a KP125 and a KP125M (or KP125M2) which is a Matter Smart Plug.

The regular KP125 is listed on the "Add a Smart Plug" Kasa menu under the "Smart Plug Lite" section which includes the classic HS103/HS105 which work under your program -- so the KP125 version *might* work at least to some extent as-is. The setup uses a temporary Wifi AP on the plug itself.

The setup for the KP125M is different and is listed under "Matter Smart Plug" -- it seems to use bluetooth to set up rather than a temporary Wifi AP (I think).

In any case I have the Matter Smart Plug :)

**Comment by jkbenaim** [comment]
I just got a KP125M. Unfortunately, it seems to support the Matter protocol exclusively. It has no support for the HS100 protocol at all, which is the only protocol that this program supports.

I'm not convinced that adding Matter support to this program is appropriate. Maybe it will happen in the future. But for now, the KP125M is simply not compatible.

Sorry about that :(

**Comment by puterboy** [comment]
The KP125 and EP25 (per TPLink they are essentially the same) seem to be non-Matter versions of the smart energy monitoring plug.
These plugs appear in the same "Add a Smart Plug" group as the HS103/HS105/KP100 whereas the KP125M appears (alone) in a new "Matter Smart Plug" category.

It seems like these plugs might be more compatible?
Have you tried them?

**Comment by jkbenaim** [comment]
I haven't tried them, but I suspect they would be compatible in that case.

**Comment by puterboy** [comment]
Just tried the EP25... which doesn't seem to work with your code.
I like it because it has the same small form factor as the mini-plug (e.g., HS03) and is cheap (I paid $20 for 2 on Amazon) yet it does the full energy monitoring.
It also falls under the same setup group in the Kasa app as the HS03 so I was hoping it would be compatible.
Unfortunately, I get a "failed to send command" error when running your code...

**Comment by puterboy** [comment]
Looking at https://github.com/python-kasa/python-kasa/discussions/548 it seems like at least the new HW/SW version of EP25 plug doesn't work. Seems like it may use AES encryption which is not yet treated in python-kasa.
Of course that would be a shame...

Could you give me your thoughts on whether this is likely to be fixed by you (or others) in the near term? Otherwise, I am tempted to just return the whole thing and either buy an older version (which supposedly is compatible) or just hold off.
Thanks!

**Comment by puterboy** [comment]
I ended up buying a (lightly) used older version of the KP125 plug that does work.
